variables:
  phpVersion: 8.1.12

image: php:$phpVersion-cli

# Composer stores all downloaded packages in the vendor/ directory.
# Do not use the following if the vendor/ directory is committed to
# your git repository.
cache:
  paths:
    - vendor/

before_script:
  - test -d vendor || apt-get update -yqq
  - test -d vendor || apt-get install -yqq curl unzip git libpq-dev libcurl4-gnutls-dev libicu-dev libvpx-dev libjpeg-dev libpng-dev libxpm-dev zlib1g-dev libfreetype6-dev libxml2-dev libexpat1-dev libbz2-dev libgmp3-dev libldap2-dev unixodbc-dev libsqlite3-dev libaspell-dev libsnmp-dev libpcre3-dev libtidy-dev libonig-dev libzip-dev
  - test -d vendor || pecl install xdebug
  - test -d vendor || docker-php-ext-enable xdebug
  - test -d vendor || docker-php-ext-install mbstring pdo_pgsql curl intl gd xml zip bz2
  - test -d vendor || curl -sS https://getcomposer.org/installer | php
  - test -d vendor || php composer.phar install


Tests:
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  allow_failure: false
  variables:
    XDEBUG_MODE: coverage
  script:
    - vendor/bin/phpunit --colors=never --log-junit phpunit-report.xml tests
    - php ./vendor/bin/phpunit --coverage-text --coverage-cobertura=coverage-cobertura.xml
  coverage: ^\s*Lines:\s*\d+.\d+\%
  artifacts:
    when: always
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage-cobertura.xml
      junit: phpunit-report.xml