version: "3.8"

volumes:
    logs:
        driver: local

services:
    php:
        container_name: slim_php
        build:
            context: ./docker/php
        ports:
            - '80:80'
        volumes:
            - .:/var/www

    mysql:
        image: mysql:latest
        container_name: mysql_todo_1
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: todos
            MYSQL_USER: todos-user
            MYSQL_PASSWORD: todos-pwd
        ports:
            - "8002:3306"
