version: "3.8"

volumes:
  logs:
    driver: local

services:
  nginx:
    restart: always
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./var/log/nginx:/var/log/nginx/
    links:
      - php-fpm
    depends_on:
      - php-fpm
      - swagger-ui
  db:
    image: mysql:latest
    restart: always
    env_file:
      - ".env"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - TZ=Europe/Paris
    ports:
      - "3306:3306"
    volumes:
      - ./var/db/mysql:/var/lib/mysql
  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - .:/var/www/html
    links:
      - db
    command: bash -c "composer install && composer make-static && php-fpm"
  swagger-ui:
    image: swaggerapi/swagger-ui
    volumes:
      - ./public/swagger/swagger.json:/usr/share/nginx/html/swagger.json
    environment:
      API_URL: swagger.json
      SWAGGER_JSON: /swagger.json
      BASE_URL: /swagger
    depends_on:
      - php-fpm